
# preload=$HOME/Pictures/Wallpaper/primeagen-miku.webp
# wallpaper=,$HOME/Pictures/Wallpaper/primeagen-miku.webp

# preload=$WALLPAPER
# wallpaper=,$WALLPAPER

splash = false

wallpaper {
    monitor = 
    path = $WALLPAPER
    fit_mode = cover
}
