# ██████╗ ██████╗  ██████╗  ██████╗ ██████╗  █████╗ ███╗   ███╗███████╗
# ██╔══██╗██╔══██╗██╔═══██╗██╔════╝ ██╔══██╗██╔══██╗████╗ ████║██╔════╝
# ██████╔╝██████╔╝██║   ██║██║  ███╗██████╔╝███████║██╔████╔██║███████╗
# ██╔═══╝ ██╔══██╗██║   ██║██║   ██║██╔══██╗██╔══██║██║╚██╔╝██║╚════██║
# ██║     ██║  ██║╚██████╔╝╚██████╔╝██║  ██║██║  ██║██║ ╚═╝ ██║███████║
# ╚═╝     ╚═╝  ╚═╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝
#----------------------------------------------------------------------

# Set programs that you use
$terminal = kitty
$fileManager = dolphin
# $menu = wofi --show drun
$menu = wofi --show drun --allow-images \
  -D key_expand=Tab \
  -D key_Down=Down \
  -D key_up=Up
# $webBrowser = google-chrome-stable
$webBrowser = firefox
$webBrowser_WithProfileManager = firefox --ProfileManager

# youtube music desktop app
$musicPlayer = chromium
