# ██████╗ ██████╗  ██████╗  ██████╗ ██████╗  █████╗ ███╗   ███╗███████╗
# ██╔══██╗██╔══██╗██╔═══██╗██╔════╝ ██╔══██╗██╔══██╗████╗ ████║██╔════╝
# ██████╔╝██████╔╝██║   ██║██║  ███╗██████╔╝███████║██╔████╔██║███████╗
# ██╔═══╝ ██╔══██╗██║   ██║██║   ██║██╔══██╗██╔══██║██║╚██╔╝██║╚════██║
# ██║     ██║  ██║╚██████╔╝╚██████╔╝██║  ██║██║  ██║██║ ╚═╝ ██║███████║
# ╚═╝     ╚═╝  ╚═╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝
#----------------------------------------------------------------------

# Set programs that you use
$terminal = kitty
$fileManager = dolphin
# $menu = wofi --show drun --allow-images \
#   -D key_expand=Tab \
#   -D key_Down=Down \
#   -D key_up=Up

$menu = rofi -show drun -theme ~/.config/rofi/applauncher.rasi
$program_menu = rofi -show window -theme ~/.config/rofi/opened-apps.rasi

# $emoji_menu = rofi -show emoji -modi emoji -theme ~/.config/rofi/emoji.rasi
$emoji_menu = rofi -show emoji -modi emoji -theme ~/.config/rofi/emoji.rasi \
    -emoji-format '<span size="33000" rise="-10000" >{emoji}</span>   {name}'

$calculator = rofi -show calc -modi calc -theme ~/.config/rofi/calc.rasi \
    -no-persist-history -no-history -lines 0

$clipboard_menu = rofi -modi \
    clipboard:~/.config/hypr/scripts/cliphist-rofi.sh \
    -show clipboard -show-icons \
    -theme ~/.config/rofi/clipboard.rasi

# $webBrowser = google-chrome-stable
$webBrowser = firefox
$webBrowser_WithProfileManager = firefox --ProfileManager

# youtube music desktop app
$musicPlayer = chromium
