# ██╗    ██╗ ██████╗ ██████╗ ██╗  ██╗███████╗██████╗  █████╗  ██████╗███████╗███████╗
# ██║    ██║██╔═══██╗██╔══██╗██║ ██╔╝██╔════╝██╔══██╗██╔══██╗██╔════╝██╔════╝██╔════╝
# ██║ █╗ ██║██║   ██║██████╔╝█████╔╝ ███████╗██████╔╝███████║██║     █████╗  ███████╗
# ██║███╗██║██║   ██║██╔══██╗██╔═██╗ ╚════██║██╔═══╝ ██╔══██║██║     ██╔══╝  ╚════██║
# ╚███╔███╔╝╚██████╔╝██║  ██║██║  ██╗███████║██║     ██║  ██║╚██████╗███████╗███████║
#  ╚══╝╚══╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝╚══════╝╚══════╝
#------------------------------------------------------------------------------------

workspace=1,monitor:$main_monitor
workspace=2,monitor:$main_monitor
workspace=3,monitor:$main_monitor
workspace=4,monitor:$main_monitor
workspace=5,monitor:$main_monitor

workspace=6,monitor:$second_monitor
workspace=7,monitor:$second_monitor
workspace=8,monitor:$second_monitor
workspace=9,monitor:$second_monitor
workspace=10,monitor:$second_monitor

