# ██╗    ██╗ ██████╗ ██████╗ ██╗  ██╗███████╗██████╗  █████╗  ██████╗███████╗███████╗
# ██║    ██║██╔═══██╗██╔══██╗██║ ██╔╝██╔════╝██╔══██╗██╔══██╗██╔════╝██╔════╝██╔════╝
# ██║ █╗ ██║██║   ██║██████╔╝█████╔╝ ███████╗██████╔╝███████║██║     █████╗  ███████╗
# ██║███╗██║██║   ██║██╔══██╗██╔═██╗ ╚════██║██╔═══╝ ██╔══██║██║     ██╔══╝  ╚════██║
# ╚███╔███╔╝╚██████╔╝██║  ██║██║  ██╗███████║██║     ██║  ██║╚██████╗███████╗███████║
#  ╚══╝╚══╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝╚══════╝╚══════╝
#------------------------------------------------------------------------------------

workspace=1,monitor:$main_monitor
workspace=2,monitor:$main_monitor
workspace=3,monitor:$main_monitor
workspace=4,monitor:$main_monitor
workspace=5,monitor:$main_monitor
workspace=6,monitor:$main_monitor
workspace=7,monitor:$main_monitor
workspace=8,monitor:$main_monitor
workspace=9,monitor:$main_monitor
workspace=10,monitor:$main_monitor

workspace=11,monitor:$second_monitor
workspace=12,monitor:$second_monitor
workspace=13,monitor:$second_monitor
workspace=14,monitor:$second_monitor
workspace=15,monitor:$second_monitor
workspace=16,monitor:$second_monitor
workspace=17,monitor:$second_monitor
workspace=18,monitor:$second_monitor
workspace=19,monitor:$second_monitor
workspace=20,monitor:$second_monitor

